name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # 3. Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4. Lint
      - name: Run Lint
        run: npm run lint

      # 5. Checagem de formatação
      - name: Check code format
        run: npm run format

      # 6. Type-check
      - name: Type check
        run: npm run type-check

      # 7. Testes
      # - name: Run tests
      #   run: npm run test

      # 8. Build
      - name: Build
        run: npm run build
